const nome = "Thaysa"

try {
  nome = "Leinane"
  console.log(nome)
}
catch(error) {
  console.error('Capturei um erro ', error)
}

console.log(nome)

console.log("proximo comando")

console.log(5*8)
